### ISSUE TITLE
bug - window glitch after resize

### ISSUE THREAD

**Issue by jergeno** [Pitchstone-Development-Group/Pitchstone-Editor#25]
If the window is resized to zero width and then restored, the entire editor viewport remains shifted to the left, making the menu bar inaccessible.  No amount of resizing and moving the window will fix the issue. The program must be closed and reopened. There is a noticable "bump" in the resize behavior, almost like Pitchstone doesn't want to shrink any more, but moving the mouse all the way to the left of the window snaps it to zero width, triggering the bug. See attached screen recordings of this behavior. 
[2024-09-24 21-03-32.zip](https://github.com/user-attachments/files/17122992/2024-09-24.21-03-32.zip)
[2024-09-24 21-01-32.zip](https://github.com/user-attachments/files/17123006/2024-09-24.21-01-32.zip)

**Comment by ari-atori** [comment]
Solved, reviewed, and merged with #26
